version: '3'
services:
  clash:
    image: clash
    container_name: clash
    volumes:
      - ./config.yaml:/root/.config/clash/config.yaml:ro
      - ./yacd:/root/.config/clash/yacd:ro
    restart: unless-stopped
    network_mode: "host"
