bind-address: 0.0.0.0
mixed-port: 7890
redir-port: 7892
allow-lan: true
external-controller: 0.0.0.0:9090
external-ui: ./yacd-meta/
ipv6: true
log-level: debug
mode: rule
profile:
  store-fake-ip: true
  store-selected: true
tcp-concurrent: true
geodata-mode: true
geox-url:
  geoip: https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geoip.dat
  geosite: https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat
  mmdb: https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/Country.mmdb
dns:
  default-nameserver:
  - 223.5.5.5
  - 119.29.29.29
  enable: true
  enhanced-mode: fake-ip
  fake-ip-filter:
  - +.lan
  - +.local
  fake-ip-range: 198.18.0.1/16
  ipv6: true
  listen: 0.0.0.0:1053
  nameserver:
  - https://doh.pub/dns-query
  - https://dns.alidns.com/dns-query
  - tls://dns.rubyfish.cn:853
  nameserver-policy:
    geosite:gfw: &id001
    - https://dns.google/dns-query
    - https://doh.opendns.com/dns-query
    geosite:greatfire: *id001
  prefer-h3: true
  proxy-server-nameserver: *id001
  use-hosts: true
proxies:
  - name: "i2p-http"
    type: http
    server: 127.0.0.1
    port: 4444
    # username: username
    # password: password
    tls: false
  - name: "i2p-socks"
    type: socks5
    server: 127.0.0.1
    port: 4447
    tls: false
proxy-groups:
- name: PROXY
  proxies:
  - LDBL
  - DIRECT
  type: select
- name: LDBL
  strategy: round-robin
  type: load-balance
- name: DEFAULT
  proxies:
  - DIRECT
  - PROXY
  type: select
rules:
- DOMAIN-SUFFIX,i2p,i2p-http
- RULE-SET,whitelist,DIRECT
secret: ''
sniffer:
  enable: true
  force-domain:
  - google.com
  skip-domain:
  - Mijia Cloud
  - dlg.io.mi.com
  - +.apple.com
  - '*.baidu.com'
  sniffing:
  - tls
  - http

extra:
  health-check:
    enable: true
    interval: 7200
    lazy: false
    url: "https://google.com"
  providers:
    - 15.235.147.69:443
    - 81.70.255.175:8080
    - free.iam7.tk
    - pi.scntvb.ml:8080
    - pic.332311.xyz:8080
    - proxies.haisto.cn
    - proxy.yiun.xyz
    - proxy.yugogo.xyz
