bind-address: 0.0.0.0
mixed-port: 7890
redir-port: 7892
allow-lan: true
external-controller: 127.0.0.1:9090
external-ui: ./yacd-meta/
ipv6: true
log-level: error
mode: rule
profile:
  store-fake-ip: true
  store-selected: true
tcp-concurrent: true
geodata-mode: true
geox-url:
  geoip: https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geoip.dat
  geosite: https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat
  mmdb: https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/Country.mmdb
dns:
  enable: true
  listen: 127.0.0.1:1053
  ipv6: true
  prefer-h3: true
  use-hosts: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
  - +.lan
  - +.local
  - +.i2p
  default-nameserver:
  # tls://dot.pub # [1.12.12.12    120.53.53.53]
  # tls://dns.alidns.com # [223.5.5.5    223.6.6.6]
  # tls://dot.360.cn # [123.6.48.18    112.65.69.15]
  - tls://120.53.53.53
  - tls://223.5.5.5
  nameserver:
  - tls://1.12.12.12
  - tls://112.65.69.15
  nameserver-policy:
    geosite:gfw: &id001
    - quic://dns-family.adguard.com
    # - quic://dns.adguard.com
    - https://doh.familyshield.opendns.com/dns-query
    # - https://doh.opendns.com/dns-query
    geosite:greatfire: *id001
  proxy-server-nameserver: *id001
proxies:
  - name: "i2p-http"
    type: http
    server: 127.0.0.1
    port: 4444
    # username: username
    # password: password
    tls: false
  - name: "i2p-socks"
    type: socks5
    server: 127.0.0.1
    port: 4447
    tls: false
proxy-groups:
- name: PROXY
  proxies:
  - LDBL
  - i2p-http
  - DIRECT
  type: select
- name: LDBL
  strategy: round-robin
  type: load-balance
rules:
- DOMAIN-SUFFIX,i2p,i2p-http
- RULE-SET,whitelist,DIRECT
secret: ''
sniffer:
  enable: true
  force-domain:
  - google.com
  skip-domain:
  - +.i2p
  - Mijia Cloud
  - dlg.io.mi.com
  - +.apple.com
  - '*.baidu.com'
  sniffing:
  - tls
  - http

extra:
  health-check:
    enable: true
    interval: 7200
    lazy: false
    url: "https://google.com"
  providers:
    - 81.70.255.175:8080
    - free.iam7.tk
    - pi.scntvb.ml:8080
    - pic.332311.xyz:8080
    - proxies.haisto.cn
    - proxy.yiun.xyz
    - proxy.yugogo.xyz
